pyms:
    services:
      swagger:
          path: "swagger"
          file: "swagger.yml"
          url: "/swagger/"
          project_dir: "project"
    config:
      APP_NAME: "Patents System Microservice"
      APP_VERSION: "1.0.0"
      APPLICATION_ROOT : "/patents-system"
      CONNECTION_STRINGS:
        POSTGRESQL_DB_SET_AS: "postgresql,pg8000,postgres:root@localhost:5432/DEV_KIBERNUM_SYSTEM"
        REDIS_EC_CROSS: "host=localhost,port=16379"
      DEBUG: true
      LANGUAGE_MULTI_SPEAK_DEFAULT_VERSION: "5.0.0"
      TESTING: true
      ENTITIES_DEFINITIONS_PATH: "static/entities_definitions.json"
