

class Constants():

    CONFIG_APP_VERSION_KEY = "APP_VERSION"
    CONFIG_CONNECTION_STRINGS_KEY = "CONNECTION_STRINGS"
    CONFIG_DATABASE_CACHE_KEYS_KEY = "DATABASE_CACHE_KEYS"
    CONFIG_DEBUG_KEY = "DEBUG"

    DATABASE_SYSTEMS = ('postgres', 'redis', 'redshift', 'sqlite', "postgresql")
    DATABASE_DRIVERS = ('pg8000', 'psycopg2')
    DATABASE_WITH_AUDIT = ('postgres', 'postgresql')

    GLOBAL_DATA_HES_KEY = "hes"
    GLOBAL_DATA_OWNER_KEY = "owner"
    GLOBAL_DATA_USER_ID_KEY = "user_id"
    GLOBAL_DATA_TRANSACTION_ID_KEY = "transaction_id"
    GLOBAL_SESSION_TRANSACTION_ID_KEY = "globalSession.transaction_id"
    GLOBAL_SESSION_USER_ID_KEY = "globalSession.user_id"
    GLOBAL_SESSION_OWNER_ID_KEY = "globalSession.owner_id"
    GLOBAL_SESSION_SOURCE_ID_KEY = "globalSession.source_id"
    GLOBAL_SESSION_SOURCE_IP_KEY = "globalSession.source_Ip"
    GLOBAL_DATA_IP_KEY = "source_ip"

    BODY_NODE_OWNER_KEY = "owner"
    BODY_NODE_OWNER_OWNER_KEY = "owner"
    BODY_PACKAGE_OWNER_ATTRIBUTES = (
        {
            "NAME": BODY_NODE_OWNER_OWNER_KEY,
            "GLOBAL_DATA_KEY": GLOBAL_DATA_OWNER_KEY,
            "REQUIRED": True
        })
    DATE_TIME_FORMATS = ("%Y-%m-%dT%H:%M:%S.%f%Z",)
    ELASTIC_CACHE_CLIENT_NAME = "elasticache"
    EXCLUDED_REQUEST_PATHS = ("swagger",)
    EXCLUDED_REQUEST_VERBS = ("OPTIONS",)
    LANGUAGE_MULTI_SPEAK_ID = "MSP"
    LANGUAGE_PRIME_ANALYTICS_PLUS_ID = "PAP"
    TYPE_REFERENCE_PRIME_ANALYTICS_PLUS = "1.0.0"
    READ_FILE_OUTPUT_TYPES = ("json", "yaml")

    REQUEST_BODY_READING_TYPE_CODE_KEY = "readingTypeCode"
    REQUEST_BODY_READING_TYPE_CODES_KEY = "readingTypeCodes"
    REQUEST_BODY_SCHEDULE_ID_KEY = "scheduleId"
    REQUEST_BODY_SCHEDULE_GUID_KEY = "scheduleGuid"
    REQUEST_BODY_VARIABLE_ID_KEY = "variableId"
    REQUEST_HEADER_OWNER_KEY = "Owner"
    REQUEST_HEADER_USER_ID_KEY = "User-Id"
    REQUEST_HEADER_TRANSACTION_ID_KEY = "Transaction-Id"
    REQUEST_HEADERS_ATTRIBUTES = (
        {
            "NAME": REQUEST_HEADER_OWNER_KEY,
            "GLOBAL_DATA_KEY": GLOBAL_DATA_OWNER_KEY,
            "REQUIRED": True
        },
        {
            "NAME": REQUEST_HEADER_TRANSACTION_ID_KEY,
            "GLOBAL_DATA_KEY": GLOBAL_DATA_TRANSACTION_ID_KEY,
            "REQUIRED": True
        },
        {
            "NAME": REQUEST_HEADER_USER_ID_KEY,
            "GLOBAL_DATA_KEY": GLOBAL_DATA_USER_ID_KEY,
            "REQUIRED": True
        })

    RESPONSE_BODY_API_VERSION_KEY = "apiVersion"
    RESPONSE_BODY_DATA_KEY = "data"
    RESPONSE_BODY_DETAIL_LEVELS_ENUM = ("Error", "Information", "Warning")
    RESPONSE_BODY_DETAILS_KEY = "details"
    RESPONSE_BODY_DETAILS_LEVEL_KEY = "level"
    RESPONSE_BODY_DETAILS_MESSAGE_KEY = "message"
    RESPONSE_BODY_DETAILS_VALUES_KEY = "values"
    RESPONSE_BODY_METHOD_KEY = "method"
    RESPONSE_BODY_RESULT_KEY = "result"
    RESPONSE_BODY_STATUS_CODE_KEY = "statusCode"
    RESPONSE_BODY_TRANSACTION_ID_KEY = "transactionId"
    RESPONSE_BODY_VARIABLE_ID_KEY = "variableId"

    SYSTEM_LOG_CATEGORY_DEBUG = "Debug"
    SYSTEM_LOG_CATEGORY_ERROR = "Error"
    SYSTEM_LOG_CATEGORY_INFORMATION = "Information"
    SYSTEM_LOG_CATEGORY_WARNING = "Warning"
    SYSTEM_LOG_CATEGORIES = {
        "DEBUG": SYSTEM_LOG_CATEGORY_DEBUG,
        "ERROR": SYSTEM_LOG_CATEGORY_ERROR,
        "INFORMATION": SYSTEM_LOG_CATEGORY_INFORMATION,
        "WARNING": SYSTEM_LOG_CATEGORY_WARNING}

    NAME_SERVICE = "PatentsSystem"
